services:
  - type: web
    name: task-manager-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: KAFKA_BOOTSTRAP_SERVERS
        sync: false
      - key: KAFKA_SASL_USERNAME
        sync: false
      - key: KAFKA_SASL_PASSWORD
        sync: false
      - key: KAFKA_TOPIC
        value: tasks-topic
      - key: KAFKA_SECURITY_PROTOCOL
        value: SASL_SSL
      - key: KAFKA_SASL_MECHANISM
        value: SCRAM-SHA-256
      - key: GEMINI_API_KEY
        sync: false
